
CREATE TABLE IF NOT EXISTS ganry(
    id_ganra SERIAL NOT NULL,
    nazvanie_ganra varchar(255) NOT NULL,
    PRIMARY KEY(id_ganra)
);
COMMENT ON TABLE ganry IS 'Жанры';
COMMENT ON COLUMN ganry.id_ganra IS 'ID_Жанра';
COMMENT ON COLUMN ganry.nazvanie_ganra IS 'Название_Жанра';

-- Generated by the database client.
CREATE TABLE IF NOT EXISTS ispolniteli(
    id_ispolnitelya SERIAL NOT NULL,
    imya_ispolnitelya varchar(255) NOT NULL,
    PRIMARY KEY(id_ispolnitelya)
);
COMMENT ON TABLE ispolniteli IS 'Исполнители';
COMMENT ON COLUMN ispolniteli.id_ispolnitelya IS 'ID_Исполнителя';
COMMENT ON COLUMN ispolniteli.imya_ispolnitelya IS 'Имя_Исполнителя';

-- Generated by the database client.
CREATE TABLE IF NOT EXISTS ispolnitely_albomy(
    id_ispolnitel_albom SERIAL NOT NULL,
    id_ispolnitelya integer NOT NULL,
    id_alboma integer NOT NULL,
    PRIMARY KEY(id_ispolnitel_albom),
    CONSTRAINT ispolnitely_albomy_id_ispolnitelya_fkey FOREIGN key(id_ispolnitelya) REFERENCES ispolniteli(id_ispolnitelya),
    CONSTRAINT ispolnitely_albomy_id_alboma_fkey FOREIGN key(id_alboma) REFERENCES albomy(id_alboma)
);
COMMENT ON TABLE ispolnitely_albomy IS 'Исполнители<=>альбомы';
COMMENT ON COLUMN ispolnitely_albomy.id_ispolnitel_albom IS 'ID_Исполнитель_Альбом';
COMMENT ON COLUMN ispolnitely_albomy.id_ispolnitelya IS 'ID_Исполнителя';
COMMENT ON COLUMN ispolnitely_albomy.id_alboma IS 'ID_Альбома';

-- Generated by the database client.
CREATE TABLE IF NOT EXISTS ispolnitely_ganry(
    id_ispolnitel_ganr SERIAL NOT NULL,
    id_ispolnitelya integer NOT NULL,
    id_ganra integer NOT NULL,
    PRIMARY KEY(id_ispolnitel_ganr),
    CONSTRAINT ispolnitely_ganry_id_ispolnitelya_fkey FOREIGN key(id_ispolnitelya) REFERENCES ispolniteli(id_ispolnitelya),
    CONSTRAINT ispolnitely_ganry_id_ganra_fkey FOREIGN key(id_ganra) REFERENCES ganry(id_ganra)
);
COMMENT ON TABLE ispolnitely_ganry IS 'Исполнители<=>Жанры';
COMMENT ON COLUMN ispolnitely_ganry.id_ispolnitel_ganr IS 'ID_Исполнитель_Жанр';
COMMENT ON COLUMN ispolnitely_ganry.id_ispolnitelya IS 'ID_Исполнителя';
COMMENT ON COLUMN ispolnitely_ganry.id_ganra IS 'ID_Жанра';

-- Generated by the database client.
CREATE TABLE IF NOT EXISTS albomy(
    id_alboma SERIAL NOT NULL,
    nazvanie_alboma varchar(255) NOT NULL,
    god_vypuska date NOT NULL,
    PRIMARY KEY(id_alboma)
);
COMMENT ON TABLE albomy IS 'Музыкальные сервисы';
COMMENT ON COLUMN albomy.nazvanie_alboma IS 'Название';
COMMENT ON COLUMN albomy.god_vypuska IS 'Год выпуска';

-- Generated by the database client.
CREATE TABLE IF NOT EXISTS sborniki(
    id_sbornika SERIAL NOT NULL,
    nazvanie_sbornika varchar(255) NOT NULL,
    god_vypuska date NOT NULL,
    PRIMARY KEY(id_sbornika)
);
COMMENT ON TABLE sborniki IS 'Сборники';
COMMENT ON COLUMN sborniki.id_sbornika IS 'ID_Сборника';
COMMENT ON COLUMN sborniki.nazvanie_sbornika IS 'Название';
COMMENT ON COLUMN sborniki.god_vypuska IS 'Год_выпуска';

-- Generated by the database client.
CREATE TABLE IF NOT EXISTS treki(
    id_treka SERIAL NOT NULL,
    nazvanie_treka varchar(255) NOT NULL,
    dlitelnost integer NOT NULL,
    id_alboma integer,
    PRIMARY KEY(id_treka),
    CONSTRAINT treki_id_alboma_fkey FOREIGN key(id_alboma) REFERENCES albomy(id_alboma)
);
COMMENT ON TABLE treki IS 'Треки';
COMMENT ON COLUMN treki.id_treka IS 'ID_Трека';
COMMENT ON COLUMN treki.nazvanie_treka IS 'Название трекака';
COMMENT ON COLUMN treki.dlitelnost IS 'Длительность';
COMMENT ON COLUMN treki.id_alboma IS 'ID_Альбома';

-- Generated by the database client.
CREATE TABLE IF NOT EXISTS treki_sbornika(
    id_trek_sbornik SERIAL NOT NULL,
    id_sbornika integer NOT NULL,
    id_treka integer NOT NULL,
    PRIMARY KEY(id_trek_sbornik),
    CONSTRAINT treki_sbornika_id_sbornika_fkey FOREIGN key(id_sbornika) REFERENCES sborniki(id_sbornika),
    CONSTRAINT treki_sbornika_id_treka_fkey FOREIGN key(id_treka) REFERENCES treki(id_treka)
);
COMMENT ON TABLE treki_sbornika IS 'Треки<=>Сборники';
COMMENT ON COLUMN treki_sbornika.id_trek_sbornik IS 'ID_Трек_Сборник';
COMMENT ON COLUMN treki_sbornika.id_sbornika IS 'ID_Сборника';
COMMENT ON COLUMN treki_sbornika.id_treka IS 'ID_Трека';